### ISSUE TITLE
interface LoadSubpackageOption参数 name类型错误，应该是string

### ISSUE THREAD

**Issue by Githubxplabs** [wechat-miniprogram/minigame-api-typings#2]
interface LoadSubpackageOption {
    /** 分包加载结束回调事件(加载成功、失败都会执行） */
    complete: Function;
    /** 分包加载失败回调事件 */
    fail: Function;
    /** 分包的名字，可以填 name 或者 root */
    name: Function;
    /** 分包加载成功回调事件 */
    success: Function;
  }

**Comment by SgLy** [comment]
fixed in 2.10.2.
